test-job:
  stage: test
  script:
    - docker-compose run -e TEST=TEST web bash -c "coverage run ./manage.py test ; coverage xml"
  only:
    - merge_request
  artifacts:
    reports:
      cobertura: coverage.xml
