test-job:
  stage: test
  script:
    - docker-compose run -e TEST=TEST web bash -c "coverage run ./manage.py test ; coverage report"
    - docker-compose run -e TEST=TEST web bash -c "coverage run ./manage.py test"
  only:
    - merge_request

upload_to_heroku:
  script:
    - git remote add heroku <https://heroku:d869af72-3901-4c71-98d4-5563d0b71fdd@git.heroku.com/enias-kompose.git>
    - git push heroku HEAD:master
  only:
    - master
